// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK1Xhr9oguAzvwA-p1vyeyASr9qRtOmv8',
    appId: '1:695282338961:web:c297c3f494ec8cd7fac330',
    messagingSenderId: '695282338961',
    projectId: 'chant-it-happens',
    authDomain: 'chant-it-happens.firebaseapp.com',
    storageBucket: 'chant-it-happens.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvi2cUuZRDJnYPyIT2VlDwsEe0xdEohDc',
    appId: '1:695282338961:android:ac6deb72fe552c2bfac330',
    messagingSenderId: '695282338961',
    projectId: 'chant-it-happens',
    storageBucket: 'chant-it-happens.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlp8RQLoiL49YNuPJV3ESW3RMB-A-Hyus',
    appId: '1:695282338961:ios:672c0c43f7af5385fac330',
    messagingSenderId: '695282338961',
    projectId: 'chant-it-happens',
    storageBucket: 'chant-it-happens.appspot.com',
    iosBundleId: 'com.example.chant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlp8RQLoiL49YNuPJV3ESW3RMB-A-Hyus',
    appId: '1:695282338961:ios:672c0c43f7af5385fac330',
    messagingSenderId: '695282338961',
    projectId: 'chant-it-happens',
    storageBucket: 'chant-it-happens.appspot.com',
    iosBundleId: 'com.example.chant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK1Xhr9oguAzvwA-p1vyeyASr9qRtOmv8',
    appId: '1:695282338961:web:30a0adba9b2759ebfac330',
    messagingSenderId: '695282338961',
    projectId: 'chant-it-happens',
    authDomain: 'chant-it-happens.firebaseapp.com',
    storageBucket: 'chant-it-happens.appspot.com',
  );
}
